version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'futspring-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: